### ISSUE TITLE
Fix HTTPS website

### ISSUE THREAD

**Issue by Jenny-Ha** [bichocj/wp-content-cna#1]
- [x] Initial evaluation of the causes of the non-application of the safety certificate

- [x] Communication of the causes to the client. @Jenny-Ha with @Kat

- [x] Solve the error about Font  "No 'Access-Control-Allow-Origin' header is present on the requested resource." @bichocj. 
View: https://docs.wp-rocket.me/article/24-resolving-issues-with-cdn-and-fonts-icons#no-header

**Comment by bichocj** [comment]
please, attach a picture with the error log @Jenny-Ha

**Comment by Jenny-Ha** [comment]
![captura de pantalla de 2018-06-22 16-50-06](https://user-images.githubusercontent.com/14958059/41800783-b4106b38-763c-11e8-8465-6e78b7974ab2.png)
El error de las fuentes estan en las primeras líneas
